name: pixi
description: Pixi - Smart AI Photo Enhancer
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ai_photo1.png
    - assets/images/ai_photo2.png
    - assets/images/ai_photo3.png
    - assets/images/pixi.png
